Adds readthedocs config file :gear:
ploomber/ploomber-engine pull request #10
Opened 2022-09-13 01:26 UTC by RodolfoFerro

2022-09-13 01:27 UTC, RodolfoFerro commented
Adds `.readthedocs.yml` config file, as well as the `env.yml` file for running the examples. Following the structure mentioned in #9

2022-09-13 13:25 UTC, edublancas requested changes

2022-09-13 13:25 UTC, edublancas commented on doc/environment.yml
> +    - ..
this last line `..` will install all these packages: https://github.com/ploomber/ploomber-engine/blob/9510173587734e7470eb90d2b1b9d5d97781c6b9/setup.py#L16 there's no need to list them one by one

2022-09-15 17:04 UTC, edublancas approved these changes

2022-09-15 17:04 UTC, merged