conf.py generated, updated environment
ploomber/ploomber-engine pull request #46
Opened 2023-02-14 19:07 UTC by gtduncan

## Describe your changes
1) Generated `conf.py` from `_config.yml`
2) Edited `.readthedocs.yml`, removed `jupyter-book config sphinx`
3) Added `pkgmt>=0.1.7` to `environment.yml`
4) Edited `conf.py` 

## Issue ticket number and link
Closes #42 

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] I have added thorough [tests](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#testing) (when necessary).
- [x] I have added the right documentation in the [docstring](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#documenting-changes-and-new-features) and [changelog](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#changelog) (when needed)

2023-02-15 22:06 UTC, gtduncan commented
Unsure why CI is failing here, all tests pass and docs build locally w/ no errors. 

Fails here during testing:

<img width="624" alt="Screen Shot 2023-02-15 at 4 56 39 PM" src="https://user-images.githubusercontent.com/106283285/219178185-98e6f893-7481-45ba-97e6-44ebe54a4741.png">
<img width="788" alt="Screen Shot 2023-02-15 at 5 03 51 PM" src="https://user-images.githubusercontent.com/106283285/219182036-0afc9f0d-c30d-4162-b930-2650c3cf415b.png">

And doc build gives this warning: 

<img width="767" alt="Screen Shot 2023-02-15 at 4 57 22 PM" src="https://user-images.githubusercontent.com/106283285/219178448-86b6f675-2dc1-4fea-8014-9a23680e9068.png">

Neither of which are present locally. They seem to both point here though, where I guess nothing is being output:

<img width="957" alt="Screen Shot 2023-02-15 at 5 00 58 PM" src="https://user-images.githubusercontent.com/106283285/219180400-78870fe3-0e98-45d1-99bd-7f84ef7bed63.png">

Which is the notebook `nb.ipynb` generated by the `test_testing.py` file in which the tests are failing. Maybe it somehow isn't being read/executed correctly under some package version? Confusing because it's not happening locally.

2023-02-16 17:01 UTC, edublancas requested changes

2023-02-16 17:01 UTC, edublancas commented on doc/conf.py
> +    "repository_branch": "main",
replace url and branch with the values returned by get_repo_and_branch_for_readthedocs

2023-02-16 19:04 UTC, edublancas approved these changes

2023-02-16 19:05 UTC, merged