Added meta info to quickstart[Issue #48]
ploomber/ploomber-engine pull request #51
Opened 2023-02-17 06:41 UTC by muddi900

## Describe your changes
Added a html-meta to `quick-start.md`. Looking for comments before I modify other docs.

## Issue ticket number and link
Closes #48

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] I have added thorough [tests](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#testing) (when necessary).
- [ ] I have added the right documentation in the [docstring](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#documenting-changes-and-new-features) and [changelog](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#changelog) (when needed)

2023-02-17 11:00 UTC, edublancas requested changes
do you want to add meta info for other .md files?

2023-02-17 11:00 UTC, edublancas commented on doc/quick-start.md
> +  "tags": "python,jupyter,notebooks"
```suggestion
  "keywords": "python,jupyter,notebooks"
```

2023-02-17 12:09 UTC, muddi900 commented
I'll probably add meta info to all docs(`*.md` and `*.rst`) as per the issue request. I'll rebase/squash commits before the final push.

2023-02-17 12:13 UTC, edublancas commented
great! please request my review when done

2023-02-22 00:43 UTC, edublancas requested changes

2023-02-22 00:43 UTC, edublancas commented on doc/api/api.rst
> +    :description lang=en: API reference for ploomber_engine
```suggestion
    :description lang=en: API reference for ploomber-engine
```

let's be consistent and use hyphen instead of underscore

2023-02-22 00:43 UTC, edublancas commented on doc/howto/pass-objects.md
> +  "description lang=en": "How to pass objects between different notebooks—Ploomber"
```suggestion
  "description lang=en": "Pass objects between notebooks using ploomber-engine"
```

2023-02-22 00:43 UTC, edublancas commented on doc/user-guide/profiling/index.md
> +  "description lang=en": ""
add description here, you can use the same description as in the github repo: "a toolbox for..."

2023-02-22 19:39 UTC, edublancas requested changes
overall it looks good! Are there any other missing files? if yes, please modify them. If not, just address my suggestions.

btw, once you make changes and want my review again, remember to click on "request review" again, this way github will notify me

2023-02-22 19:39 UTC, edublancas commented on doc/quick-start.md
> +  "description lang=en": "A quick-start guide for ploomber-engine, a toolbox for exeuting jupyter notebooks"
```suggestion
  "description lang=en": "A quick-start guide for ploomber-engine, a toolbox for executing jupyter notebooks"
```

2023-02-22 19:39 UTC, edublancas commented on doc/user-guide/debugging/debuglater.md
> +  "description lang=en": "How to use the debuglater package."
```suggestion
  "description lang=en": "How to use ploomber-engine with the debuglater package."
```

2023-03-02 01:35 UTC, merged